name: CI/CD en DockerHub y Render
on:
  push:
    branches: 
    - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3